#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-zabbix-agent-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix-agent-conf' => '10'
);

templates2events("/etc/zabbix/zabbix_agentd.conf", $event);
templates2events("/etc/zabbix/zabbix_agent2.conf", $event);
templates2events("/etc/nethserver/eorepo.conf", $event);

event_services($event,
               'zabbix-agent' => 'restart',
               'zabbix-agent2' => 'restart'
);
