#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

if [[ ! -f "/etc/zabbix/psk.shared" ]];then 
    /usr/bin/openssl rand -hex 32 > /etc/zabbix/psk.shared
    /usr/bin/chown zabbix:zabbix /etc/zabbix/psk.shared
    /usr/bin/chmod 400 /etc/zabbix/psk.shared
fi
